### ISSUE TITLE
8 bit Sound Blaster DOS distortion fix

### ISSUE THREAD

**Issue by LeonG-ZA** [msikma/allegro-4.2.2-xc#3]
Back in 2008 there was a thread about distorted sound on the Allegro 4.2.2 version when using 8-bit Sound Blasters:
https://www.allegro.cc/forums/thread/596505/0

Apparently the bug was located in "sb.c", but the last change in this repo was from 2006. Does anyone know if these changes were ever committed? I don't have a real 8-bit Sound Blaster to test with.

**Comment by LeonG-ZA** [comment]
I see that there is a pull request for the fix. Please ignore

**Comment by msikma** [comment]
Thanks for reminding me that these things exist! I've basically totally ignored this repo but I should really just merge those PRs.

**Comment by msikma** [comment]
There we go, merged.
